import { beforeEach, describe, expect, it } from 'vitest';

import { createAuthDependencies } from '../test-support/auth-doubles.js';
import {
  createPublicUserFixture,
  createRegistrationInput,
  createUserFixture,
  GENERATED_PASSWORD_HASH,
} from '../test-support/auth-fixtures.js';
import {
  createRegisterUserSubject,
  MissingAuthenticationBehaviourError,
} from '../test-support/auth-subjects.js';

async function captureExpectedError(operation: () => Promise<unknown>): Promise<unknown> {
  try {
    await operation();
  } catch (error) {
    if (error instanceof MissingAuthenticationBehaviourError) {
      throw error;
    }

    return error;
  }

  throw new Error('Expected registration to fail');
}

describe('register user', () => {
  let dependencies: ReturnType<typeof createAuthDependencies>;
  let registerUser: ReturnType<typeof createRegisterUserSubject>;

  beforeEach(() => {
    dependencies = createAuthDependencies();
    registerUser = createRegisterUserSubject(dependencies);
  });

  it('registers a user with valid details', async () => {
    const input = createRegistrationInput();

    const user = await registerUser.execute(input);

    expect(dependencies.userRepository.create).toHaveBeenCalledOnce();
    expect(user).toEqual(createPublicUserFixture());
  });

  it('trims leading and trailing whitespace from the name', async () => {
    const input = createRegistrationInput({ name: '  Mahadev  ' });

    await registerUser.execute(input);

    expect(dependencies.userRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({ name: 'Mahadev' }),
    );
  });

  it('trims leading and trailing whitespace from the email', async () => {
    const input = createRegistrationInput({ email: '  mahadev@example.com  ' });

    await registerUser.execute(input);

    expect(dependencies.userRepository.findByEmail).toHaveBeenCalledWith('mahadev@example.com');
    expect(dependencies.userRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({ email: 'mahadev@example.com' }),
    );
  });

  it('converts the email to lowercase', async () => {
    const input = createRegistrationInput({ email: 'Mahadev@Example.COM' });

    await registerUser.execute(input);

    expect(dependencies.userRepository.findByEmail).toHaveBeenCalledWith('mahadev@example.com');
  });

  it('looks up duplicate users using the normalized email', async () => {
    const input = createRegistrationInput({ email: '  Mahadev@Example.COM  ' });

    await registerUser.execute(input);

    expect(dependencies.userRepository.findByEmail).toHaveBeenCalledOnce();
    expect(dependencies.userRepository.findByEmail).toHaveBeenCalledWith('mahadev@example.com');
  });

  it('persists the normalized email', async () => {
    const input = createRegistrationInput({ email: '  Mahadev@Example.COM  ' });

    await registerUser.execute(input);

    expect(dependencies.userRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({ email: 'mahadev@example.com' }),
    );
  });

  it('passes the plain password to the password hasher', async () => {
    const input = createRegistrationInput();

    await registerUser.execute(input);

    expect(dependencies.passwordHasher.hash).toHaveBeenCalledOnce();
    expect(dependencies.passwordHasher.hash).toHaveBeenCalledWith(input.password);
  });

  it('persists the password hash generated by the password hasher', async () => {
    await registerUser.execute(createRegistrationInput());

    expect(dependencies.userRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({ passwordHash: GENERATED_PASSWORD_HASH }),
    );
  });

  it('never persists the plain-text password', async () => {
    const input = createRegistrationInput();

    await registerUser.execute(input);

    const [persistedUser] = dependencies.userRepository.create.mock.calls[0] ?? [];
    expect(persistedUser).toBeDefined();
    expect(persistedUser).not.toHaveProperty('password');
    expect(persistedUser?.passwordHash).not.toBe(input.password);
  });

  it('creates a user with the USER role by default', async () => {
    await registerUser.execute(createRegistrationInput());

    expect(dependencies.userRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({ role: 'USER' }),
    );
  });

  it('ignores a client-supplied ADMIN role and creates a USER account', async () => {
    const input = createRegistrationInput({ role: 'ADMIN' });

    const user = await registerUser.execute(input);

    expect(dependencies.userRepository.create).toHaveBeenCalledWith(
      expect.objectContaining({ role: 'USER' }),
    );
    expect(user.role).toBe('USER');
  });

  it('returns sanitized public user information', async () => {
    const user = await registerUser.execute(createRegistrationInput());

    expect(user).toEqual(createPublicUserFixture());
  });

  it('does not return the password hash', async () => {
    const user = await registerUser.execute(createRegistrationInput());

    expect(user).not.toHaveProperty('passwordHash');
    expect(user).not.toHaveProperty('password');
  });

  it('rejects registration with a conflict error when the email already exists', async () => {
    dependencies.userRepository.findByEmail.mockResolvedValue(createUserFixture());

    const error = await captureExpectedError(() =>
      registerUser.execute(createRegistrationInput({ email: '  MAHADEV@example.com  ' })),
    );

    expect(error).toMatchObject({ code: 'EMAIL_ALREADY_EXISTS' });
  });

  it('does not create a user when the normalized email already exists', async () => {
    dependencies.userRepository.findByEmail.mockResolvedValue(createUserFixture());

    await captureExpectedError(() => registerUser.execute(createRegistrationInput()));

    expect(dependencies.userRepository.create).not.toHaveBeenCalled();
    expect(dependencies.passwordHasher.hash).not.toHaveBeenCalled();
  });

  it('does not hash or persist data when registration validation fails', async () => {
    await captureExpectedError(() =>
      registerUser.execute(createRegistrationInput({ name: '   ' })),
    );

    expect(dependencies.passwordHasher.hash).not.toHaveBeenCalled();
    expect(dependencies.userRepository.create).not.toHaveBeenCalled();
  });

  it('handles password-hasher failure without leaking sensitive details', async () => {
    const input = createRegistrationInput();
    dependencies.passwordHasher.hash.mockRejectedValue(
      new Error(`Hasher failed while processing ${input.password}`),
    );

    const error = await captureExpectedError(() => registerUser.execute(input));

    expect(error).toMatchObject({
      code: 'UNEXPECTED_ERROR',
      message: 'An unexpected error occurred.',
    });
    expect(String(error)).not.toContain(input.password);
  });

  it('handles repository failure through the shared unexpected-error mechanism', async () => {
    dependencies.userRepository.findByEmail.mockRejectedValue(
      new Error('Prisma connection details must remain internal'),
    );

    const error = await captureExpectedError(() => registerUser.execute(createRegistrationInput()));

    expect(error).toMatchObject({
      code: 'UNEXPECTED_ERROR',
      message: 'An unexpected error occurred.',
    });
    expect(String(error)).not.toContain('Prisma');
  });
});
